on:
  release:
    types:
      - published
      - unpublished
      - deleted
jobs:
  trigger-doc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install HTTPie
        run: sudo snap install --edge httpie
      - name: Trigger website build
        run: http --ignore-stdin POST ${{ secrets.PIE_WEB_VERCEL_HOOK }}
